### ISSUE TITLE
Upgrade the example

### ISSUE THREAD

**Issue by jabrena** [okteto/java-maven-getting-started#7]
I am going to review the example to upgrade:

- Dockerfile -> Upgrade to Java 17
- pom.xml -> Upgrade from Spring Boot 2.1.8.RELEASE to Spring Boot 3

**Comment by pchico83** [comment]
@jabrena that would be awesome, thanks!

**Comment by jabrena** [comment]
Hi @pchico83,

I have few questions about [okteto.yml](https://github.com/okteto/java-maven-getting-started/blob/main/okteto.yml)

The Docker image is generated from this section:

``` 
build:
  hello-world:
    image: okteto.dev/java-maven-hello-world:1.0.0
    context: .
``` 

Does exist a way to run a `maven` goal like:

```
mvn package spring-boot:buildImage
```

or it is possible to run a bash script for complex scenarios?

Where is located the documentation about `octeto.yml`?
